name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          #git clone --depth 1 https://github.com/quictls/quictls.git
          git clone -b cmake-doc-install https://github.com/quictls/quictls quictls
          cd quictls
          cmake . 
          make
          sudo make install
